spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/
    username: root
    password: root
  sql:
    init:
      mode: always