logging:
  level:
    org.springframework.security: TRACE

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_security
    username: root
    password: root